# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default
  # vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      npm install --prefix ./AngularTest/
      echo Hello world

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'AngularTest'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'AngularTest'
    customCommand: 'run ng build --prod'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'AngularTest/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
